# Generated by Django 3.2.10 on 2021-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='solana', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='solana', max_length=20),
            preserve_default=False,
        ),
    ]
