# Generated by Django 3.2.10 on 2021-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bg_color',
            field=models.CharField(default='aqua', max_length=18, verbose_name='رنگ پس زمینه'),
        ),
    ]
