# Generated by Django 3.2.10 on 2021-12-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='bg_color',
        ),
    ]
