# Generated by Django 3.2.10 on 2021-12-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=2048, verbose_name='نام دوره')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='categories', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(blank=True, verbose_name='ترتیب')),
                ('vod_url', models.CharField(max_length=4194304, verbose_name='آدرس ویدیو')),
                ('is_demo', models.BooleanField(default=False, help_text='ویدیو به صورت دمو قابل مشاده باشد', verbose_name='دمو')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'ویدیو ها',
                'ordering': ['order'],
            },
        ),
    ]
